### ISSUE TITLE
Error while compiling code at mac os

### ISSUE THREAD

**Issue by arlesfarias** [trocolit2/Project_M#2]
There is an error in the building process on 92%. I have opencv 2.4.12 installed on my mac.
![screenshot 2016-03-18 13 40 50](https://cloud.githubusercontent.com/assets/10709351/13885009/493ce01a-ed0f-11e5-8121-1da9cf33eee3.png)
Which one version of opencv should I have installed on my machine?

**Comment by trocolit2** [comment]
Hay @arlesfarias, I will check the issue on my MAC and will give you some feedback.
But, a superficial analysis, I suppose it's a problem in CMake library linkage, on CMakeList.txt inside test folder.

**Comment by trocolit2** [comment]
@arlesfarias, I advise you to install this Project_M on UBUNTU 14.XX oh 15.XX

**Comment by arlesfarias** [comment]
Hey @trocolit2, I`ve manually included opencv on CMakeLists.txt and it works!

![screenshot 2016-03-19 07 41 39](https://cloud.githubusercontent.com/assets/10709351/13898098/5c8149f8-eda6-11e5-852b-10c12131de51.png)

Really was a linkage issue. Thanks for help.

**Comment by trocolit2** [comment]
@arlesfarias Thanks!! I will change my code as you suggested.
